/*
 * API League
 *
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: mail@apileague.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using apileague.Model;
using apileague.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace apileague.Test.Model
{
    /// <summary>
    ///  Class for testing DetectLanguageAPI200ResponseInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DetectLanguageAPI200ResponseInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DetectLanguageAPI200ResponseInner
        //private DetectLanguageAPI200ResponseInner instance;

        public DetectLanguageAPI200ResponseInnerTests()
        {
            // TODO uncomment below to create an instance of DetectLanguageAPI200ResponseInner
            //instance = new DetectLanguageAPI200ResponseInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DetectLanguageAPI200ResponseInner
        /// </summary>
        [Fact]
        public void DetectLanguageAPI200ResponseInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" DetectLanguageAPI200ResponseInner
            //Assert.IsType<DetectLanguageAPI200ResponseInner>(instance);
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

        /// <summary>
        /// Test the property 'Confidence'
        /// </summary>
        [Fact]
        public void ConfidenceTest()
        {
            // TODO unit test for the property 'Confidence'
        }
    }
}
