/*
 * API League
 *
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.6.3
 * Contact: mail@apileague.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using apileague.Model;
using apileague.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace apileague.Test.Model
{
    /// <summary>
    ///  Class for testing RetrieveRecipeInformation200ResponseNutrition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RetrieveRecipeInformation200ResponseNutritionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RetrieveRecipeInformation200ResponseNutrition
        //private RetrieveRecipeInformation200ResponseNutrition instance;

        public RetrieveRecipeInformation200ResponseNutritionTests()
        {
            // TODO uncomment below to create an instance of RetrieveRecipeInformation200ResponseNutrition
            //instance = new RetrieveRecipeInformation200ResponseNutrition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RetrieveRecipeInformation200ResponseNutrition
        /// </summary>
        [Fact]
        public void RetrieveRecipeInformation200ResponseNutritionInstanceTest()
        {
            // TODO uncomment below to test "IsType" RetrieveRecipeInformation200ResponseNutrition
            //Assert.IsType<RetrieveRecipeInformation200ResponseNutrition>(instance);
        }

        /// <summary>
        /// Test the property 'WeightPerServing'
        /// </summary>
        [Fact]
        public void WeightPerServingTest()
        {
            // TODO unit test for the property 'WeightPerServing'
        }

        /// <summary>
        /// Test the property 'CaloricBreakdown'
        /// </summary>
        [Fact]
        public void CaloricBreakdownTest()
        {
            // TODO unit test for the property 'CaloricBreakdown'
        }

        /// <summary>
        /// Test the property 'Flavonoids'
        /// </summary>
        [Fact]
        public void FlavonoidsTest()
        {
            // TODO unit test for the property 'Flavonoids'
        }

        /// <summary>
        /// Test the property 'IngredientBreakdown'
        /// </summary>
        [Fact]
        public void IngredientBreakdownTest()
        {
            // TODO unit test for the property 'IngredientBreakdown'
        }

        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }

        /// <summary>
        /// Test the property 'Nutrients'
        /// </summary>
        [Fact]
        public void NutrientsTest()
        {
            // TODO unit test for the property 'Nutrients'
        }
    }
}
