/*
 * API League
 *
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.4.2
 * Contact: mail@apileague.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using apileague.Model;
using apileague.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace apileague.Test.Model
{
    /// <summary>
    ///  Class for testing RetrieveRecipeInformation200ResponseIngredientsInnerMeasuresMetric
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RetrieveRecipeInformation200ResponseIngredientsInnerMeasuresMetricTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RetrieveRecipeInformation200ResponseIngredientsInnerMeasuresMetric
        //private RetrieveRecipeInformation200ResponseIngredientsInnerMeasuresMetric instance;

        public RetrieveRecipeInformation200ResponseIngredientsInnerMeasuresMetricTests()
        {
            // TODO uncomment below to create an instance of RetrieveRecipeInformation200ResponseIngredientsInnerMeasuresMetric
            //instance = new RetrieveRecipeInformation200ResponseIngredientsInnerMeasuresMetric();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RetrieveRecipeInformation200ResponseIngredientsInnerMeasuresMetric
        /// </summary>
        [Fact]
        public void RetrieveRecipeInformation200ResponseIngredientsInnerMeasuresMetricInstanceTest()
        {
            // TODO uncomment below to test "IsType" RetrieveRecipeInformation200ResponseIngredientsInnerMeasuresMetric
            //Assert.IsType<RetrieveRecipeInformation200ResponseIngredientsInnerMeasuresMetric>(instance);
        }

        /// <summary>
        /// Test the property 'UnitShort'
        /// </summary>
        [Fact]
        public void UnitShortTest()
        {
            // TODO unit test for the property 'UnitShort'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'UnitLong'
        /// </summary>
        [Fact]
        public void UnitLongTest()
        {
            // TODO unit test for the property 'UnitLong'
        }
    }
}
