/*
 * API League
 *
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mail@apileague.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using apileague.Model;
using apileague.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace apileague.Test.Model
{
    /// <summary>
    ///  Class for testing ScoreText200ResponseStyleSubscores
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScoreText200ResponseStyleSubscoresTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScoreText200ResponseStyleSubscores
        //private ScoreText200ResponseStyleSubscores instance;

        public ScoreText200ResponseStyleSubscoresTests()
        {
            // TODO uncomment below to create an instance of ScoreText200ResponseStyleSubscores
            //instance = new ScoreText200ResponseStyleSubscores();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScoreText200ResponseStyleSubscores
        /// </summary>
        [Fact]
        public void ScoreText200ResponseStyleSubscoresInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScoreText200ResponseStyleSubscores
            //Assert.IsType<ScoreText200ResponseStyleSubscores>(instance);
        }

        /// <summary>
        /// Test the property 'AbbreviationScore'
        /// </summary>
        [Fact]
        public void AbbreviationScoreTest()
        {
            // TODO unit test for the property 'AbbreviationScore'
        }

        /// <summary>
        /// Test the property 'StyleScore'
        /// </summary>
        [Fact]
        public void StyleScoreTest()
        {
            // TODO unit test for the property 'StyleScore'
        }

        /// <summary>
        /// Test the property 'SpellingScore'
        /// </summary>
        [Fact]
        public void SpellingScoreTest()
        {
            // TODO unit test for the property 'SpellingScore'
        }
    }
}
