/*
 * API League
 *
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.6.4
 * Contact: mail@apileague.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using apileague.Model;
using apileague.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace apileague.Test.Model
{
    /// <summary>
    ///  Class for testing SearchDrinksAPI200ResponseDrinksInnerCredits
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchDrinksAPI200ResponseDrinksInnerCreditsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchDrinksAPI200ResponseDrinksInnerCredits
        //private SearchDrinksAPI200ResponseDrinksInnerCredits instance;

        public SearchDrinksAPI200ResponseDrinksInnerCreditsTests()
        {
            // TODO uncomment below to create an instance of SearchDrinksAPI200ResponseDrinksInnerCredits
            //instance = new SearchDrinksAPI200ResponseDrinksInnerCredits();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchDrinksAPI200ResponseDrinksInnerCredits
        /// </summary>
        [Fact]
        public void SearchDrinksAPI200ResponseDrinksInnerCreditsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchDrinksAPI200ResponseDrinksInnerCredits
            //Assert.IsType<SearchDrinksAPI200ResponseDrinksInnerCredits>(instance);
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'SourceName'
        /// </summary>
        [Fact]
        public void SourceNameTest()
        {
            // TODO unit test for the property 'SourceName'
        }

        /// <summary>
        /// Test the property 'SourceUrl'
        /// </summary>
        [Fact]
        public void SourceUrlTest()
        {
            // TODO unit test for the property 'SourceUrl'
        }
    }
}
