/*
 * API League
 *
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.7.0
 * Contact: mail@apileague.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using apileague.Model;
using apileague.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace apileague.Test.Model
{
    /// <summary>
    ///  Class for testing VectorSearchAPI200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VectorSearchAPI200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VectorSearchAPI200Response
        //private VectorSearchAPI200Response instance;

        public VectorSearchAPI200ResponseTests()
        {
            // TODO uncomment below to create an instance of VectorSearchAPI200Response
            //instance = new VectorSearchAPI200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VectorSearchAPI200Response
        /// </summary>
        [Fact]
        public void VectorSearchAPI200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" VectorSearchAPI200Response
            //Assert.IsType<VectorSearchAPI200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Vectors'
        /// </summary>
        [Fact]
        public void VectorsTest()
        {
            // TODO unit test for the property 'Vectors'
        }
    }
}
