=begin
#API League

#API League is a Hub for World Class APIs.

The version of the OpenAPI document: 1.6.3
Contact: mail@apileague.com
Generated by: https://openapi-generator.tech
Generator version: 7.8.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::SearchDrinks200ResponseDrinksInnerNutritionIngredientBreakdownInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::SearchDrinks200ResponseDrinksInnerNutritionIngredientBreakdownInner do
  let(:instance) { OpenapiClient::SearchDrinks200ResponseDrinksInnerNutritionIngredientBreakdownInner.new }

  describe 'test an instance of SearchDrinks200ResponseDrinksInnerNutritionIngredientBreakdownInner' do
    it 'should create an instance of SearchDrinks200ResponseDrinksInnerNutritionIngredientBreakdownInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::SearchDrinks200ResponseDrinksInnerNutritionIngredientBreakdownInner)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "amount"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "unit"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "nutrients"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
