# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule com.apileague.client.Model.InlineResponse20018Readability do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"mainscores",
    :"subscores"
  ]

  @type t :: %__MODULE__{
    :"mainscores" => com.apileague.client.Model.InlineResponse20018ReadabilityMainscores.t | nil,
    :"subscores" => com.apileague.client.Model.InlineResponse20018ReadabilitySubscores.t | nil
  }
end

defimpl Poison.Decoder, for: com.apileague.client.Model.InlineResponse20018Readability do
  import com.apileague.client.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"mainscores", :struct, com.apileague.client.Model.InlineResponse20018ReadabilityMainscores, options)
    |> deserialize(:"subscores", :struct, com.apileague.client.Model.InlineResponse20018ReadabilitySubscores, options)
  end
end

