# coding: utf-8

"""
    API League

    API League is a Hub for World Class APIs.

    The version of the OpenAPI document: 1.7.0
    Contact: mail@apileague.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from apileague.models.random_poem_api200_response import RandomPoemAPI200Response

class TestRandomPoemAPI200Response(unittest.TestCase):
    """RandomPoemAPI200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RandomPoemAPI200Response:
        """Test RandomPoemAPI200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RandomPoemAPI200Response`
        """
        model = RandomPoemAPI200Response()
        if include_optional:
            return RandomPoemAPI200Response(
                title = '',
                author = '',
                poem = ''
            )
        else:
            return RandomPoemAPI200Response(
        )
        """

    def testRandomPoemAPI200Response(self):
        """Test RandomPoemAPI200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
