# coding: utf-8

"""
    API League

    API League is a Hub for World Class APIs.

    The version of the OpenAPI document: 1.8.1
    Contact: mail@apileague.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from apileague.models.search_drinks_api200_response_drinks_inner_ingredients_inner_measures_metric import SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric

class TestSearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric(unittest.TestCase):
    """SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric:
        """Test SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric`
        """
        model = SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric()
        if include_optional:
            return SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric(
                unit_short = '',
                amount = 1.337,
                unit_long = ''
            )
        else:
            return SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric(
        )
        """

    def testSearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric(self):
        """Test SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
