/**
 * API League
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.6.4
 * Contact: mail@apileague.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ComputeNutritionAPI200ResponseIngredientBreakdownInner from './ComputeNutritionAPI200ResponseIngredientBreakdownInner';
import SearchDrinksAPI200ResponseDrinksInnerNutritionCaloricBreakdown from './SearchDrinksAPI200ResponseDrinksInnerNutritionCaloricBreakdown';
import SearchDrinksAPI200ResponseDrinksInnerNutritionFlavonoidsInner from './SearchDrinksAPI200ResponseDrinksInnerNutritionFlavonoidsInner';
import SearchDrinksAPI200ResponseDrinksInnerNutritionNutrientsInner from './SearchDrinksAPI200ResponseDrinksInnerNutritionNutrientsInner';
import SearchDrinksAPI200ResponseDrinksInnerNutritionWeightPerServing from './SearchDrinksAPI200ResponseDrinksInnerNutritionWeightPerServing';
import SearchRecipesAPI200ResponseRecipesInnerNutritionNutrientsInner from './SearchRecipesAPI200ResponseRecipesInnerNutritionNutrientsInner';

/**
 * The ComputeNutritionAPI200Response model module.
 * @module model/ComputeNutritionAPI200Response
 * @version 1.6.4
 */
class ComputeNutritionAPI200Response {
    /**
     * Constructs a new <code>ComputeNutritionAPI200Response</code>.
     * @alias module:model/ComputeNutritionAPI200Response
     */
    constructor() { 
        
        ComputeNutritionAPI200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ComputeNutritionAPI200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ComputeNutritionAPI200Response} obj Optional instance to populate.
     * @return {module:model/ComputeNutritionAPI200Response} The populated <code>ComputeNutritionAPI200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ComputeNutritionAPI200Response();

            if (data.hasOwnProperty('nutrients')) {
                obj['nutrients'] = ApiClient.convertToType(data['nutrients'], [SearchDrinksAPI200ResponseDrinksInnerNutritionNutrientsInner]);
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], [SearchDrinksAPI200ResponseDrinksInnerNutritionFlavonoidsInner]);
            }
            if (data.hasOwnProperty('flavonoids')) {
                obj['flavonoids'] = ApiClient.convertToType(data['flavonoids'], [SearchRecipesAPI200ResponseRecipesInnerNutritionNutrientsInner]);
            }
            if (data.hasOwnProperty('ingredient_breakdown')) {
                obj['ingredient_breakdown'] = ApiClient.convertToType(data['ingredient_breakdown'], [ComputeNutritionAPI200ResponseIngredientBreakdownInner]);
            }
            if (data.hasOwnProperty('caloric_breakdown')) {
                obj['caloric_breakdown'] = SearchDrinksAPI200ResponseDrinksInnerNutritionCaloricBreakdown.constructFromObject(data['caloric_breakdown']);
            }
            if (data.hasOwnProperty('weight_per_serving')) {
                obj['weight_per_serving'] = SearchDrinksAPI200ResponseDrinksInnerNutritionWeightPerServing.constructFromObject(data['weight_per_serving']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ComputeNutritionAPI200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ComputeNutritionAPI200Response</code>.
     */
    static validateJSON(data) {
        if (data['nutrients']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['nutrients'])) {
                throw new Error("Expected the field `nutrients` to be an array in the JSON data but got " + data['nutrients']);
            }
            // validate the optional field `nutrients` (array)
            for (const item of data['nutrients']) {
                SearchDrinksAPI200ResponseDrinksInnerNutritionNutrientsInner.validateJSON(item);
            };
        }
        if (data['properties']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['properties'])) {
                throw new Error("Expected the field `properties` to be an array in the JSON data but got " + data['properties']);
            }
            // validate the optional field `properties` (array)
            for (const item of data['properties']) {
                SearchDrinksAPI200ResponseDrinksInnerNutritionFlavonoidsInner.validateJSON(item);
            };
        }
        if (data['flavonoids']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['flavonoids'])) {
                throw new Error("Expected the field `flavonoids` to be an array in the JSON data but got " + data['flavonoids']);
            }
            // validate the optional field `flavonoids` (array)
            for (const item of data['flavonoids']) {
                SearchRecipesAPI200ResponseRecipesInnerNutritionNutrientsInner.validateJSON(item);
            };
        }
        if (data['ingredient_breakdown']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['ingredient_breakdown'])) {
                throw new Error("Expected the field `ingredient_breakdown` to be an array in the JSON data but got " + data['ingredient_breakdown']);
            }
            // validate the optional field `ingredient_breakdown` (array)
            for (const item of data['ingredient_breakdown']) {
                ComputeNutritionAPI200ResponseIngredientBreakdownInner.validateJSON(item);
            };
        }
        // validate the optional field `caloric_breakdown`
        if (data['caloric_breakdown']) { // data not null
          SearchDrinksAPI200ResponseDrinksInnerNutritionCaloricBreakdown.validateJSON(data['caloric_breakdown']);
        }
        // validate the optional field `weight_per_serving`
        if (data['weight_per_serving']) { // data not null
          SearchDrinksAPI200ResponseDrinksInnerNutritionWeightPerServing.validateJSON(data['weight_per_serving']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/SearchDrinksAPI200ResponseDrinksInnerNutritionNutrientsInner>} nutrients
 */
ComputeNutritionAPI200Response.prototype['nutrients'] = undefined;

/**
 * @member {Array.<module:model/SearchDrinksAPI200ResponseDrinksInnerNutritionFlavonoidsInner>} properties
 */
ComputeNutritionAPI200Response.prototype['properties'] = undefined;

/**
 * @member {Array.<module:model/SearchRecipesAPI200ResponseRecipesInnerNutritionNutrientsInner>} flavonoids
 */
ComputeNutritionAPI200Response.prototype['flavonoids'] = undefined;

/**
 * @member {Array.<module:model/ComputeNutritionAPI200ResponseIngredientBreakdownInner>} ingredient_breakdown
 */
ComputeNutritionAPI200Response.prototype['ingredient_breakdown'] = undefined;

/**
 * @member {module:model/SearchDrinksAPI200ResponseDrinksInnerNutritionCaloricBreakdown} caloric_breakdown
 */
ComputeNutritionAPI200Response.prototype['caloric_breakdown'] = undefined;

/**
 * @member {module:model/SearchDrinksAPI200ResponseDrinksInnerNutritionWeightPerServing} weight_per_serving
 */
ComputeNutritionAPI200Response.prototype['weight_per_serving'] = undefined;






export default ComputeNutritionAPI200Response;

