{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE PartialTypeSignatures #-}

module Main where

import Data.Typeable (Proxy(..))
import Test.Hspec
import Test.Hspec.QuickCheck

import PropMime
import Instances ()

import APILeague.Model
import APILeague.MimeTypes

main :: IO ()
main =
  hspec $ modifyMaxSize (const 10) $ do
    describe "JSON instances" $ do
      pure ()
      propMimeEq MimeJSON (Proxy :: Proxy ComputeNutrition200Response)
      propMimeEq MimeJSON (Proxy :: Proxy ComputeNutrition200ResponseIngredientBreakdownInner)
      propMimeEq MimeJSON (Proxy :: Proxy ComputeNutrition200ResponseIngredientBreakdownInnerNutrientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy ConvertUnits200Response)
      propMimeEq MimeJSON (Proxy :: Proxy CorrectSpelling200Response)
      propMimeEq MimeJSON (Proxy :: Proxy DetectGenderByName200Response)
      propMimeEq MimeJSON (Proxy :: Proxy DetectLanguage200ResponseInner)
      propMimeEq MimeJSON (Proxy :: Proxy DetectMainImageColor200ResponseInner)
      propMimeEq MimeJSON (Proxy :: Proxy DetectSentiment200Response)
      propMimeEq MimeJSON (Proxy :: Proxy DetectSentiment200ResponseDocument)
      propMimeEq MimeJSON (Proxy :: Proxy DetectSentiment200ResponseSentencesInner)
      propMimeEq MimeJSON (Proxy :: Proxy ExtractAuthors200Response)
      propMimeEq MimeJSON (Proxy :: Proxy ExtractAuthors200ResponseAuthorsInner)
      propMimeEq MimeJSON (Proxy :: Proxy ExtractContentFromAWebPage200Response)
      propMimeEq MimeJSON (Proxy :: Proxy ExtractDates200Response)
      propMimeEq MimeJSON (Proxy :: Proxy ExtractDates200ResponseDatesInner)
      propMimeEq MimeJSON (Proxy :: Proxy ExtractEntities200Response)
      propMimeEq MimeJSON (Proxy :: Proxy ExtractEntities200ResponseEntitiesInner)
      propMimeEq MimeJSON (Proxy :: Proxy ExtractNews200Response)
      propMimeEq MimeJSON (Proxy :: Proxy ExtractNews200ResponseImagesInner)
      propMimeEq MimeJSON (Proxy :: Proxy ExtractNews200ResponseVideosInner)
      propMimeEq MimeJSON (Proxy :: Proxy ExtractPublishDate200Response)
      propMimeEq MimeJSON (Proxy :: Proxy FindSimilarBooks200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GenerateNonsenseWord200Response)
      propMimeEq MimeJSON (Proxy :: Proxy ListWordSynonyms200Response)
      propMimeEq MimeJSON (Proxy :: Proxy PluralizeWord200Response)
      propMimeEq MimeJSON (Proxy :: Proxy RandomMeme200Response)
      propMimeEq MimeJSON (Proxy :: Proxy RandomPoem200Response)
      propMimeEq MimeJSON (Proxy :: Proxy RandomQuote200Response)
      propMimeEq MimeJSON (Proxy :: Proxy RandomRiddle200Response)
      propMimeEq MimeJSON (Proxy :: Proxy RandomTrivia200Response)
      propMimeEq MimeJSON (Proxy :: Proxy ReadKeyValueFromStore200Response)
      propMimeEq MimeJSON (Proxy :: Proxy RetrievePageRank200Response)
      propMimeEq MimeJSON (Proxy :: Proxy RetrieveRecipeInformation200Response)
      propMimeEq MimeJSON (Proxy :: Proxy RetrieveRecipeInformation200ResponseCredits)
      propMimeEq MimeJSON (Proxy :: Proxy RetrieveRecipeInformation200ResponseDietaryProperties)
      propMimeEq MimeJSON (Proxy :: Proxy RetrieveRecipeInformation200ResponseIngredientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy RetrieveRecipeInformation200ResponseIngredientsInnerMeasures)
      propMimeEq MimeJSON (Proxy :: Proxy RetrieveRecipeInformation200ResponseInstructionsInner)
      propMimeEq MimeJSON (Proxy :: Proxy RetrieveRecipeInformation200ResponseInstructionsInnerStepsInner)
      propMimeEq MimeJSON (Proxy :: Proxy RetrieveRecipeInformation200ResponseNutrition)
      propMimeEq MimeJSON (Proxy :: Proxy RetrieveRecipeInformation200ResponseNutritionIngredientBreakdownInner)
      propMimeEq MimeJSON (Proxy :: Proxy RetrieveRecipeInformation200ResponseScores)
      propMimeEq MimeJSON (Proxy :: Proxy RetrieveRecipeInformation200ResponseTaste)
      propMimeEq MimeJSON (Proxy :: Proxy RetrieveRecipeInformation200ResponseTimes)
      propMimeEq MimeJSON (Proxy :: Proxy ScoreReadability200Response)
      propMimeEq MimeJSON (Proxy :: Proxy ScoreText200Response)
      propMimeEq MimeJSON (Proxy :: Proxy ScoreText200ResponseInterestingness)
      propMimeEq MimeJSON (Proxy :: Proxy ScoreText200ResponseInterestingnessSubscores)
      propMimeEq MimeJSON (Proxy :: Proxy ScoreText200ResponseReadability)
      propMimeEq MimeJSON (Proxy :: Proxy ScoreText200ResponseReadabilityMainscores)
      propMimeEq MimeJSON (Proxy :: Proxy ScoreText200ResponseReadabilitySubscores)
      propMimeEq MimeJSON (Proxy :: Proxy ScoreText200ResponseSkimmability)
      propMimeEq MimeJSON (Proxy :: Proxy ScoreText200ResponseSkimmabilityMainscores)
      propMimeEq MimeJSON (Proxy :: Proxy ScoreText200ResponseSkimmabilitySubscores)
      propMimeEq MimeJSON (Proxy :: Proxy ScoreText200ResponseStyle)
      propMimeEq MimeJSON (Proxy :: Proxy ScoreText200ResponseStyleSubscores)
      propMimeEq MimeJSON (Proxy :: Proxy SearchBooks200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchBooks200ResponseBooksInnerInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchDrinks200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchDrinks200ResponseDrinksInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchDrinks200ResponseDrinksInnerCredits)
      propMimeEq MimeJSON (Proxy :: Proxy SearchDrinks200ResponseDrinksInnerIngredientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchDrinks200ResponseDrinksInnerIngredientsInnerMeasures)
      propMimeEq MimeJSON (Proxy :: Proxy SearchDrinks200ResponseDrinksInnerIngredientsInnerMeasuresMetric)
      propMimeEq MimeJSON (Proxy :: Proxy SearchDrinks200ResponseDrinksInnerIngredientsInnerMeasuresUs)
      propMimeEq MimeJSON (Proxy :: Proxy SearchDrinks200ResponseDrinksInnerInstructionsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchDrinks200ResponseDrinksInnerInstructionsInnerStepsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchDrinks200ResponseDrinksInnerInstructionsInnerStepsInnerIngredientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchDrinks200ResponseDrinksInnerNutrition)
      propMimeEq MimeJSON (Proxy :: Proxy SearchDrinks200ResponseDrinksInnerNutritionCaloricBreakdown)
      propMimeEq MimeJSON (Proxy :: Proxy SearchDrinks200ResponseDrinksInnerNutritionFlavonoidsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchDrinks200ResponseDrinksInnerNutritionIngredientBreakdownInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchDrinks200ResponseDrinksInnerNutritionIngredientBreakdownInnerNutrientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchDrinks200ResponseDrinksInnerNutritionNutrientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchDrinks200ResponseDrinksInnerNutritionWeightPerServing)
      propMimeEq MimeJSON (Proxy :: Proxy SearchGifs200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchGifs200ResponseImagesInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchIcons200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchJokes200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchJokes200ResponseJokesInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchMemes200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchMemes200ResponseMemesInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchNews200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchNews200ResponseNewsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchRecipes200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchRecipes200ResponseRecipesInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchRecipes200ResponseRecipesInnerNutrition)
      propMimeEq MimeJSON (Proxy :: Proxy SearchRecipes200ResponseRecipesInnerNutritionNutrientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchRestaurants200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchRestaurants200ResponseRestaurantsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchRestaurants200ResponseRestaurantsInnerAddress)
      propMimeEq MimeJSON (Proxy :: Proxy SearchRestaurants200ResponseRestaurantsInnerLocalHours)
      propMimeEq MimeJSON (Proxy :: Proxy SearchRestaurants200ResponseRestaurantsInnerLocalHoursOperational)
      propMimeEq MimeJSON (Proxy :: Proxy SearchRoyaltyFreeImages200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchRoyaltyFreeImages200ResponseImagesInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchRoyaltyFreeImages200ResponseImagesInnerLicense)
      propMimeEq MimeJSON (Proxy :: Proxy SearchWeb200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchWeb200ResponseResultsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SingularizeWord200Response)
      propMimeEq MimeJSON (Proxy :: Proxy StemText200Response)
      propMimeEq MimeJSON (Proxy :: Proxy StoreKeyValueGET200Response)
      propMimeEq MimeJSON (Proxy :: Proxy TagPartOfSpeech200Response)
      propMimeEq MimeJSON (Proxy :: Proxy TopNews200Response)
      propMimeEq MimeJSON (Proxy :: Proxy TopNews200ResponseTopNewsInner)
      propMimeEq MimeJSON (Proxy :: Proxy TopNews200ResponseTopNewsInnerNewsInner)
      propMimeEq MimeJSON (Proxy :: Proxy VerifyEmailAddress200Response)
      
