/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.apileague.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.apileague.client.model.ExtractAuthorsAPI200Response
import com.apileague.client.model.ExtractAuthorsAPI200ResponseAuthorsInner

class ExtractAuthorsAPI200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExtractAuthorsAPI200Response
        //val modelInstance = ExtractAuthorsAPI200Response()

        // to test the property `authors`
        should("test authors") {
            // uncomment below to test the property
            //modelInstance.authors shouldBe ("TODO")
        }

    }
}
