/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.apileague.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.apileague.client.model.RandomTrivia200Response

class RandomTrivia200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RandomTrivia200Response
        //val modelInstance = RandomTrivia200Response()

        // to test the property `trivia`
        should("test trivia") {
            // uncomment below to test the property
            //modelInstance.trivia shouldBe ("TODO")
        }

    }
}
