/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.apileague.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.apileague.client.model.RandomRiddleAPI200Response

class RandomRiddleAPI200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RandomRiddleAPI200Response
        //val modelInstance = RandomRiddleAPI200Response()

        // to test the property `riddle`
        should("test riddle") {
            // uncomment below to test the property
            //modelInstance.riddle shouldBe ("TODO")
        }

        // to test the property `answer`
        should("test answer") {
            // uncomment below to test the property
            //modelInstance.answer shouldBe ("TODO")
        }

        // to test the property `difficulty`
        should("test difficulty") {
            // uncomment below to test the property
            //modelInstance.difficulty shouldBe ("TODO")
        }

    }
}
