/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.apileague.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.apileague.client.model.ScoreText200ResponseInterestingnessSubscores

class ScoreText200ResponseInterestingnessSubscoresTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ScoreText200ResponseInterestingnessSubscores
        //val modelInstance = ScoreText200ResponseInterestingnessSubscores()

        // to test the property `titleRatingScore`
        should("test titleRatingScore") {
            // uncomment below to test the property
            //modelInstance.titleRatingScore shouldBe ("TODO")
        }

        // to test the property `quoteScore`
        should("test quoteScore") {
            // uncomment below to test the property
            //modelInstance.quoteScore shouldBe ("TODO")
        }

        // to test the property `lengthScore`
        should("test lengthScore") {
            // uncomment below to test the property
            //modelInstance.lengthScore shouldBe ("TODO")
        }

        // to test the property `linkScore`
        should("test linkScore") {
            // uncomment below to test the property
            //modelInstance.linkScore shouldBe ("TODO")
        }

        // to test the property `googleHitsScore`
        should("test googleHitsScore") {
            // uncomment below to test the property
            //modelInstance.googleHitsScore shouldBe ("TODO")
        }

    }
}
