/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.apileague.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.apileague.client.model.SearchRoyaltyFreeImages200ResponseImagesInner
import com.apileague.client.model.SearchRoyaltyFreeImages200ResponseImagesInnerLicense

class SearchRoyaltyFreeImages200ResponseImagesInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SearchRoyaltyFreeImages200ResponseImagesInner
        //val modelInstance = SearchRoyaltyFreeImages200ResponseImagesInner()

        // to test the property `width`
        should("test width") {
            // uncomment below to test the property
            //modelInstance.width shouldBe ("TODO")
        }

        // to test the property `license`
        should("test license") {
            // uncomment below to test the property
            //modelInstance.license shouldBe ("TODO")
        }

        // to test the property `thumbnail`
        should("test thumbnail") {
            // uncomment below to test the property
            //modelInstance.thumbnail shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `height`
        should("test height") {
            // uncomment below to test the property
            //modelInstance.height shouldBe ("TODO")
        }

    }
}
