/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.apileague.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.apileague.client.model.TopNews200ResponseTopNewsInner
import com.apileague.client.model.TopNews200ResponseTopNewsInnerNewsInner

class TopNews200ResponseTopNewsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TopNews200ResponseTopNewsInner
        //val modelInstance = TopNews200ResponseTopNewsInner()

        // to test the property `news`
        should("test news") {
            // uncomment below to test the property
            //modelInstance.news shouldBe ("TODO")
        }

    }
}
