/*
 * API League
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.7.0
 * Contact: mail@apileague.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.apileague.client;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    static {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ArtSearchAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ComputeNutritionAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ComputeNutritionAPI200ResponseIngredientBreakdownInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ComputeNutritionAPI200ResponseIngredientBreakdownInnerNutrientsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ConvertUnitsAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.CorrectSpellingAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.DetectGenderByNameAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.DetectLanguageAPI200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.DetectMainImageColorAPI200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.DetectSentimentAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.DetectSentimentAPI200ResponseDocument.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.DetectSentimentAPI200ResponseSentencesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ExtractAuthorsAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ExtractAuthorsAPI200ResponseAuthorsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ExtractContentFromAWebPageAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ExtractDatesAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ExtractDatesAPI200ResponseDatesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ExtractEntitiesAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ExtractEntitiesAPI200ResponseEntitiesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ExtractNewsAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ExtractNewsAPI200ResponseImagesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ExtractNewsAPI200ResponseVideosInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ExtractPublishDateAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.FindSimilarBooksAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.GenerateNonsenseWordAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ListWordSynonymsAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.PluralizeWordAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.RandomMemeAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.RandomPoemAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.RandomQuoteAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.RandomRiddleAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.RandomTriviaAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ReadKeyValueFromStoreAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.RetrieveArtworkById200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.RetrievePageRankAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.RetrieveRecipeInformationAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.RetrieveRecipeInformationAPI200ResponseCredits.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.RetrieveRecipeInformationAPI200ResponseDietaryProperties.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.RetrieveRecipeInformationAPI200ResponseIngredientsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.RetrieveRecipeInformationAPI200ResponseInstructionsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.RetrieveRecipeInformationAPI200ResponseInstructionsInnerStepsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.RetrieveRecipeInformationAPI200ResponseNutrition.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.RetrieveRecipeInformationAPI200ResponseNutritionIngredientBreakdownInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.RetrieveRecipeInformationAPI200ResponseScores.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.RetrieveRecipeInformationAPI200ResponseTaste.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.RetrieveRecipeInformationAPI200ResponseTimes.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ScoreReadabilityAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ScoreTextAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ScoreTextAPI200ResponseInterestingness.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ScoreTextAPI200ResponseInterestingnessSubscores.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ScoreTextAPI200ResponseReadability.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ScoreTextAPI200ResponseReadabilityMainscores.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ScoreTextAPI200ResponseReadabilitySubscores.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ScoreTextAPI200ResponseSkimmability.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ScoreTextAPI200ResponseSkimmabilityMainscores.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ScoreTextAPI200ResponseSkimmabilitySubscores.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ScoreTextAPI200ResponseStyle.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.ScoreTextAPI200ResponseStyleSubscores.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchBooksAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchBooksAPI200ResponseBooksInnerInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchDrinksAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchDrinksAPI200ResponseDrinksInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchDrinksAPI200ResponseDrinksInnerCredits.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchDrinksAPI200ResponseDrinksInnerIngredientsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasures.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresUs.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchDrinksAPI200ResponseDrinksInnerInstructionsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchDrinksAPI200ResponseDrinksInnerInstructionsInnerStepsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchDrinksAPI200ResponseDrinksInnerInstructionsInnerStepsInnerIngredientsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchDrinksAPI200ResponseDrinksInnerNutrition.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchDrinksAPI200ResponseDrinksInnerNutritionCaloricBreakdown.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchDrinksAPI200ResponseDrinksInnerNutritionFlavonoidsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchDrinksAPI200ResponseDrinksInnerNutritionIngredientBreakdownInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchDrinksAPI200ResponseDrinksInnerNutritionIngredientBreakdownInnerNutrientsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchDrinksAPI200ResponseDrinksInnerNutritionNutrientsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchDrinksAPI200ResponseDrinksInnerNutritionWeightPerServing.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchGifsAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchGifsAPI200ResponseImagesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchIconsAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchJokesAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchJokesAPI200ResponseJokesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchMemesAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchMemesAPI200ResponseMemesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchNewsAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchNewsAPI200ResponseNewsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchRecipesAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchRecipesAPI200ResponseRecipesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchRecipesAPI200ResponseRecipesInnerNutrition.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchRecipesAPI200ResponseRecipesInnerNutritionNutrientsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchRestaurantsAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchRestaurantsAPI200ResponseRestaurantsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchRestaurantsAPI200ResponseRestaurantsInnerAddress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchRestaurantsAPI200ResponseRestaurantsInnerLocalHours.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchRestaurantsAPI200ResponseRestaurantsInnerLocalHoursOperational.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchRoyaltyFreeImagesAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchRoyaltyFreeImagesAPI200ResponseImagesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchRoyaltyFreeImagesAPI200ResponseImagesInnerLicense.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchWebAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SearchWebAPI200ResponseResultsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.SingularizeWordAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.StemTextAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.StoreKeyValueGETAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.TagPartOfSpeechAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.TopNewsAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.TopNewsAPI200ResponseTopNewsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.TopNewsAPI200ResponseTopNewsInnerNewsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.VectorSearchAPI200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.VectorSearchAPI200ResponseVectorsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.apileague.client.model.VerifyEmailAddressAPI200Response.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
