export * from './art.service';
import { ArtService } from './art.service';
export * from './books.service';
import { BooksService } from './books.service';
export * from './food.service';
import { FoodService } from './food.service';
export * from './games.service';
import { GamesService } from './games.service';
export * from './humor.service';
import { HumorService } from './humor.service';
export * from './knowledge.service';
import { KnowledgeService } from './knowledge.service';
export * from './math.service';
import { MathService } from './math.service';
export * from './media.service';
import { MediaService } from './media.service';
export * from './news.service';
import { NewsService } from './news.service';
export * from './storage.service';
import { StorageService } from './storage.service';
export * from './text.service';
import { TextService } from './text.service';
export * from './web.service';
import { WebService } from './web.service';
export const APIS = [ArtService, BooksService, FoodService, GamesService, HumorService, KnowledgeService, MathService, MediaService, NewsService, StorageService, TextService, WebService];
