--[[
  API League

  API League is a Hub for World Class APIs.

  The version of the OpenAPI document: 1.6.2
  Contact: mail@apileague.com
  Generated by: https://openapi-generator.tech
]]

-- score_text_200_response class
local score_text_200_response = {}
local score_text_200_response_mt = {
	__name = "score_text_200_response";
	__index = score_text_200_response;
}

local function cast_score_text_200_response(t)
	return setmetatable(t, score_text_200_response_mt)
end

local function new_score_text_200_response(number_of_words, number_of_sentences, readability, skimmability, interestingness, style, total_score)
	return cast_score_text_200_response({
		["number_of_words"] = number_of_words;
		["number_of_sentences"] = number_of_sentences;
		["readability"] = readability;
		["skimmability"] = skimmability;
		["interestingness"] = interestingness;
		["style"] = style;
		["total_score"] = total_score;
	})
end

return {
	cast = cast_score_text_200_response;
	new = new_score_text_200_response;
}
