/*
 * API League
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.6.4
 * Contact: mail@apileague.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.apileague.client.model;

import java.util.Objects;
import com.apileague.client.model.SearchRestaurantsAPI200ResponseRestaurantsInnerAddress;
import com.apileague.client.model.SearchRestaurantsAPI200ResponseRestaurantsInnerLocalHours;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.apileague.client.JSON;

/**
 * SearchRestaurantsAPI200ResponseRestaurantsInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0-SNAPSHOT")
public class SearchRestaurantsAPI200ResponseRestaurantsInner {
  public static final String SERIALIZED_NAME_OFFERS_THIRD_PARTY_DELIVERY = "offers_third_party_delivery";
  @SerializedName(SERIALIZED_NAME_OFFERS_THIRD_PARTY_DELIVERY)
  private Boolean offersThirdPartyDelivery;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private SearchRestaurantsAPI200ResponseRestaurantsInnerAddress address;

  public static final String SERIALIZED_NAME_SUPPORTS_UPC_CODES = "supports_upc_codes";
  @SerializedName(SERIALIZED_NAME_SUPPORTS_UPC_CODES)
  private Boolean supportsUpcCodes;

  public static final String SERIALIZED_NAME_IS_OPEN = "is_open";
  @SerializedName(SERIALIZED_NAME_IS_OPEN)
  private Boolean isOpen;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_WEIGHTED_RATING_VALUE = "weighted_rating_value";
  @SerializedName(SERIALIZED_NAME_WEIGHTED_RATING_VALUE)
  private Integer weightedRatingValue;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_OFFERS_FIRST_PARTY_DELIVERY = "offers_first_party_delivery";
  @SerializedName(SERIALIZED_NAME_OFFERS_FIRST_PARTY_DELIVERY)
  private Boolean offersFirstPartyDelivery;

  public static final String SERIALIZED_NAME_AGGREGATED_RATING_COUNT = "aggregated_rating_count";
  @SerializedName(SERIALIZED_NAME_AGGREGATED_RATING_COUNT)
  private Integer aggregatedRatingCount;

  public static final String SERIALIZED_NAME_PICKUP_ENABLED = "pickup_enabled";
  @SerializedName(SERIALIZED_NAME_PICKUP_ENABLED)
  private Boolean pickupEnabled;

  public static final String SERIALIZED_NAME_CUISINES = "cuisines";
  @SerializedName(SERIALIZED_NAME_CUISINES)
  private List<String> cuisines = new ArrayList<>();

  public static final String SERIALIZED_NAME_MILES = "miles";
  @SerializedName(SERIALIZED_NAME_MILES)
  private BigDecimal miles;

  public static final String SERIALIZED_NAME_DOLLAR_SIGNS = "dollar_signs";
  @SerializedName(SERIALIZED_NAME_DOLLAR_SIGNS)
  private Integer dollarSigns;

  public static final String SERIALIZED_NAME_DELIVERY_ENABLED = "delivery_enabled";
  @SerializedName(SERIALIZED_NAME_DELIVERY_ENABLED)
  private Boolean deliveryEnabled;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PHONE_NUMBER = "phone_number";
  @SerializedName(SERIALIZED_NAME_PHONE_NUMBER)
  private BigDecimal phoneNumber;

  public static final String SERIALIZED_NAME_ID = "_id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_LOCAL_HOURS = "local_hours";
  @SerializedName(SERIALIZED_NAME_LOCAL_HOURS)
  private SearchRestaurantsAPI200ResponseRestaurantsInnerLocalHours localHours;

  public SearchRestaurantsAPI200ResponseRestaurantsInner() {
  }

  public SearchRestaurantsAPI200ResponseRestaurantsInner offersThirdPartyDelivery(Boolean offersThirdPartyDelivery) {
    this.offersThirdPartyDelivery = offersThirdPartyDelivery;
    return this;
  }

  /**
   * Get offersThirdPartyDelivery
   * @return offersThirdPartyDelivery
   */
  @javax.annotation.Nullable
  public Boolean getOffersThirdPartyDelivery() {
    return offersThirdPartyDelivery;
  }

  public void setOffersThirdPartyDelivery(Boolean offersThirdPartyDelivery) {
    this.offersThirdPartyDelivery = offersThirdPartyDelivery;
  }


  public SearchRestaurantsAPI200ResponseRestaurantsInner address(SearchRestaurantsAPI200ResponseRestaurantsInnerAddress address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @javax.annotation.Nullable
  public SearchRestaurantsAPI200ResponseRestaurantsInnerAddress getAddress() {
    return address;
  }

  public void setAddress(SearchRestaurantsAPI200ResponseRestaurantsInnerAddress address) {
    this.address = address;
  }


  public SearchRestaurantsAPI200ResponseRestaurantsInner supportsUpcCodes(Boolean supportsUpcCodes) {
    this.supportsUpcCodes = supportsUpcCodes;
    return this;
  }

  /**
   * Get supportsUpcCodes
   * @return supportsUpcCodes
   */
  @javax.annotation.Nullable
  public Boolean getSupportsUpcCodes() {
    return supportsUpcCodes;
  }

  public void setSupportsUpcCodes(Boolean supportsUpcCodes) {
    this.supportsUpcCodes = supportsUpcCodes;
  }


  public SearchRestaurantsAPI200ResponseRestaurantsInner isOpen(Boolean isOpen) {
    this.isOpen = isOpen;
    return this;
  }

  /**
   * Get isOpen
   * @return isOpen
   */
  @javax.annotation.Nullable
  public Boolean getIsOpen() {
    return isOpen;
  }

  public void setIsOpen(Boolean isOpen) {
    this.isOpen = isOpen;
  }


  public SearchRestaurantsAPI200ResponseRestaurantsInner description(String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public SearchRestaurantsAPI200ResponseRestaurantsInner weightedRatingValue(Integer weightedRatingValue) {
    this.weightedRatingValue = weightedRatingValue;
    return this;
  }

  /**
   * Get weightedRatingValue
   * @return weightedRatingValue
   */
  @javax.annotation.Nullable
  public Integer getWeightedRatingValue() {
    return weightedRatingValue;
  }

  public void setWeightedRatingValue(Integer weightedRatingValue) {
    this.weightedRatingValue = weightedRatingValue;
  }


  public SearchRestaurantsAPI200ResponseRestaurantsInner type(String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  public SearchRestaurantsAPI200ResponseRestaurantsInner offersFirstPartyDelivery(Boolean offersFirstPartyDelivery) {
    this.offersFirstPartyDelivery = offersFirstPartyDelivery;
    return this;
  }

  /**
   * Get offersFirstPartyDelivery
   * @return offersFirstPartyDelivery
   */
  @javax.annotation.Nullable
  public Boolean getOffersFirstPartyDelivery() {
    return offersFirstPartyDelivery;
  }

  public void setOffersFirstPartyDelivery(Boolean offersFirstPartyDelivery) {
    this.offersFirstPartyDelivery = offersFirstPartyDelivery;
  }


  public SearchRestaurantsAPI200ResponseRestaurantsInner aggregatedRatingCount(Integer aggregatedRatingCount) {
    this.aggregatedRatingCount = aggregatedRatingCount;
    return this;
  }

  /**
   * Get aggregatedRatingCount
   * @return aggregatedRatingCount
   */
  @javax.annotation.Nullable
  public Integer getAggregatedRatingCount() {
    return aggregatedRatingCount;
  }

  public void setAggregatedRatingCount(Integer aggregatedRatingCount) {
    this.aggregatedRatingCount = aggregatedRatingCount;
  }


  public SearchRestaurantsAPI200ResponseRestaurantsInner pickupEnabled(Boolean pickupEnabled) {
    this.pickupEnabled = pickupEnabled;
    return this;
  }

  /**
   * Get pickupEnabled
   * @return pickupEnabled
   */
  @javax.annotation.Nullable
  public Boolean getPickupEnabled() {
    return pickupEnabled;
  }

  public void setPickupEnabled(Boolean pickupEnabled) {
    this.pickupEnabled = pickupEnabled;
  }


  public SearchRestaurantsAPI200ResponseRestaurantsInner cuisines(List<String> cuisines) {
    this.cuisines = cuisines;
    return this;
  }

  public SearchRestaurantsAPI200ResponseRestaurantsInner addCuisinesItem(String cuisinesItem) {
    if (this.cuisines == null) {
      this.cuisines = new ArrayList<>();
    }
    this.cuisines.add(cuisinesItem);
    return this;
  }

  /**
   * Get cuisines
   * @return cuisines
   */
  @javax.annotation.Nullable
  public List<String> getCuisines() {
    return cuisines;
  }

  public void setCuisines(List<String> cuisines) {
    this.cuisines = cuisines;
  }


  public SearchRestaurantsAPI200ResponseRestaurantsInner miles(BigDecimal miles) {
    this.miles = miles;
    return this;
  }

  /**
   * Get miles
   * @return miles
   */
  @javax.annotation.Nullable
  public BigDecimal getMiles() {
    return miles;
  }

  public void setMiles(BigDecimal miles) {
    this.miles = miles;
  }


  public SearchRestaurantsAPI200ResponseRestaurantsInner dollarSigns(Integer dollarSigns) {
    this.dollarSigns = dollarSigns;
    return this;
  }

  /**
   * Get dollarSigns
   * @return dollarSigns
   */
  @javax.annotation.Nullable
  public Integer getDollarSigns() {
    return dollarSigns;
  }

  public void setDollarSigns(Integer dollarSigns) {
    this.dollarSigns = dollarSigns;
  }


  public SearchRestaurantsAPI200ResponseRestaurantsInner deliveryEnabled(Boolean deliveryEnabled) {
    this.deliveryEnabled = deliveryEnabled;
    return this;
  }

  /**
   * Get deliveryEnabled
   * @return deliveryEnabled
   */
  @javax.annotation.Nullable
  public Boolean getDeliveryEnabled() {
    return deliveryEnabled;
  }

  public void setDeliveryEnabled(Boolean deliveryEnabled) {
    this.deliveryEnabled = deliveryEnabled;
  }


  public SearchRestaurantsAPI200ResponseRestaurantsInner name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public SearchRestaurantsAPI200ResponseRestaurantsInner phoneNumber(BigDecimal phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

  /**
   * Get phoneNumber
   * @return phoneNumber
   */
  @javax.annotation.Nullable
  public BigDecimal getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(BigDecimal phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  public SearchRestaurantsAPI200ResponseRestaurantsInner id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public SearchRestaurantsAPI200ResponseRestaurantsInner localHours(SearchRestaurantsAPI200ResponseRestaurantsInnerLocalHours localHours) {
    this.localHours = localHours;
    return this;
  }

  /**
   * Get localHours
   * @return localHours
   */
  @javax.annotation.Nullable
  public SearchRestaurantsAPI200ResponseRestaurantsInnerLocalHours getLocalHours() {
    return localHours;
  }

  public void setLocalHours(SearchRestaurantsAPI200ResponseRestaurantsInnerLocalHours localHours) {
    this.localHours = localHours;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchRestaurantsAPI200ResponseRestaurantsInner searchRestaurantsAPI200ResponseRestaurantsInner = (SearchRestaurantsAPI200ResponseRestaurantsInner) o;
    return Objects.equals(this.offersThirdPartyDelivery, searchRestaurantsAPI200ResponseRestaurantsInner.offersThirdPartyDelivery) &&
        Objects.equals(this.address, searchRestaurantsAPI200ResponseRestaurantsInner.address) &&
        Objects.equals(this.supportsUpcCodes, searchRestaurantsAPI200ResponseRestaurantsInner.supportsUpcCodes) &&
        Objects.equals(this.isOpen, searchRestaurantsAPI200ResponseRestaurantsInner.isOpen) &&
        Objects.equals(this.description, searchRestaurantsAPI200ResponseRestaurantsInner.description) &&
        Objects.equals(this.weightedRatingValue, searchRestaurantsAPI200ResponseRestaurantsInner.weightedRatingValue) &&
        Objects.equals(this.type, searchRestaurantsAPI200ResponseRestaurantsInner.type) &&
        Objects.equals(this.offersFirstPartyDelivery, searchRestaurantsAPI200ResponseRestaurantsInner.offersFirstPartyDelivery) &&
        Objects.equals(this.aggregatedRatingCount, searchRestaurantsAPI200ResponseRestaurantsInner.aggregatedRatingCount) &&
        Objects.equals(this.pickupEnabled, searchRestaurantsAPI200ResponseRestaurantsInner.pickupEnabled) &&
        Objects.equals(this.cuisines, searchRestaurantsAPI200ResponseRestaurantsInner.cuisines) &&
        Objects.equals(this.miles, searchRestaurantsAPI200ResponseRestaurantsInner.miles) &&
        Objects.equals(this.dollarSigns, searchRestaurantsAPI200ResponseRestaurantsInner.dollarSigns) &&
        Objects.equals(this.deliveryEnabled, searchRestaurantsAPI200ResponseRestaurantsInner.deliveryEnabled) &&
        Objects.equals(this.name, searchRestaurantsAPI200ResponseRestaurantsInner.name) &&
        Objects.equals(this.phoneNumber, searchRestaurantsAPI200ResponseRestaurantsInner.phoneNumber) &&
        Objects.equals(this.id, searchRestaurantsAPI200ResponseRestaurantsInner.id) &&
        Objects.equals(this.localHours, searchRestaurantsAPI200ResponseRestaurantsInner.localHours);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(offersThirdPartyDelivery, address, supportsUpcCodes, isOpen, description, weightedRatingValue, type, offersFirstPartyDelivery, aggregatedRatingCount, pickupEnabled, cuisines, miles, dollarSigns, deliveryEnabled, name, phoneNumber, id, localHours);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchRestaurantsAPI200ResponseRestaurantsInner {\n");
    sb.append("    offersThirdPartyDelivery: ").append(toIndentedString(offersThirdPartyDelivery)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    supportsUpcCodes: ").append(toIndentedString(supportsUpcCodes)).append("\n");
    sb.append("    isOpen: ").append(toIndentedString(isOpen)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    weightedRatingValue: ").append(toIndentedString(weightedRatingValue)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    offersFirstPartyDelivery: ").append(toIndentedString(offersFirstPartyDelivery)).append("\n");
    sb.append("    aggregatedRatingCount: ").append(toIndentedString(aggregatedRatingCount)).append("\n");
    sb.append("    pickupEnabled: ").append(toIndentedString(pickupEnabled)).append("\n");
    sb.append("    cuisines: ").append(toIndentedString(cuisines)).append("\n");
    sb.append("    miles: ").append(toIndentedString(miles)).append("\n");
    sb.append("    dollarSigns: ").append(toIndentedString(dollarSigns)).append("\n");
    sb.append("    deliveryEnabled: ").append(toIndentedString(deliveryEnabled)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    localHours: ").append(toIndentedString(localHours)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("offers_third_party_delivery");
    openapiFields.add("address");
    openapiFields.add("supports_upc_codes");
    openapiFields.add("is_open");
    openapiFields.add("description");
    openapiFields.add("weighted_rating_value");
    openapiFields.add("type");
    openapiFields.add("offers_first_party_delivery");
    openapiFields.add("aggregated_rating_count");
    openapiFields.add("pickup_enabled");
    openapiFields.add("cuisines");
    openapiFields.add("miles");
    openapiFields.add("dollar_signs");
    openapiFields.add("delivery_enabled");
    openapiFields.add("name");
    openapiFields.add("phone_number");
    openapiFields.add("_id");
    openapiFields.add("local_hours");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SearchRestaurantsAPI200ResponseRestaurantsInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SearchRestaurantsAPI200ResponseRestaurantsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SearchRestaurantsAPI200ResponseRestaurantsInner is not found in the empty JSON string", SearchRestaurantsAPI200ResponseRestaurantsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SearchRestaurantsAPI200ResponseRestaurantsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SearchRestaurantsAPI200ResponseRestaurantsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `address`
      if (jsonObj.get("address") != null && !jsonObj.get("address").isJsonNull()) {
        SearchRestaurantsAPI200ResponseRestaurantsInnerAddress.validateJsonElement(jsonObj.get("address"));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("cuisines") != null && !jsonObj.get("cuisines").isJsonNull() && !jsonObj.get("cuisines").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `cuisines` to be an array in the JSON string but got `%s`", jsonObj.get("cuisines").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("_id") != null && !jsonObj.get("_id").isJsonNull()) && !jsonObj.get("_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("_id").toString()));
      }
      // validate the optional field `local_hours`
      if (jsonObj.get("local_hours") != null && !jsonObj.get("local_hours").isJsonNull()) {
        SearchRestaurantsAPI200ResponseRestaurantsInnerLocalHours.validateJsonElement(jsonObj.get("local_hours"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SearchRestaurantsAPI200ResponseRestaurantsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SearchRestaurantsAPI200ResponseRestaurantsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SearchRestaurantsAPI200ResponseRestaurantsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SearchRestaurantsAPI200ResponseRestaurantsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<SearchRestaurantsAPI200ResponseRestaurantsInner>() {
           @Override
           public void write(JsonWriter out, SearchRestaurantsAPI200ResponseRestaurantsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SearchRestaurantsAPI200ResponseRestaurantsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SearchRestaurantsAPI200ResponseRestaurantsInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SearchRestaurantsAPI200ResponseRestaurantsInner
   * @throws IOException if the JSON string is invalid with respect to SearchRestaurantsAPI200ResponseRestaurantsInner
   */
  public static SearchRestaurantsAPI200ResponseRestaurantsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SearchRestaurantsAPI200ResponseRestaurantsInner.class);
  }

  /**
   * Convert an instance of SearchRestaurantsAPI200ResponseRestaurantsInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

