/**
 * API League
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: mail@apileague.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DetectSentiment200ResponseSentencesInner } from './detectSentiment200ResponseSentencesInner';
import { DetectSentiment200ResponseDocument } from './detectSentiment200ResponseDocument';


export interface DetectSentiment200Response { 
    document?: DetectSentiment200ResponseDocument;
    sentences?: Array<DetectSentiment200ResponseSentencesInner>;
}

