/*
 * API League
 *
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.6.3
 * Contact: mail@apileague.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = apileague.Client.OpenAPIDateConverter;

namespace apileague.Model
{
    /// <summary>
    /// FindSimilarBooks200Response
    /// </summary>
    [DataContract(Name = "findSimilarBooks_200_response")]
    public partial class FindSimilarBooks200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FindSimilarBooks200Response" /> class.
        /// </summary>
        /// <param name="similarBooks">similarBooks.</param>
        public FindSimilarBooks200Response(List<SearchBooks200ResponseBooksInnerInner> similarBooks = default(List<SearchBooks200ResponseBooksInnerInner>))
        {
            this.SimilarBooks = similarBooks;
        }

        /// <summary>
        /// Gets or Sets SimilarBooks
        /// </summary>
        [DataMember(Name = "similar_books", EmitDefaultValue = false)]
        public List<SearchBooks200ResponseBooksInnerInner> SimilarBooks { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FindSimilarBooks200Response {\n");
            sb.Append("  SimilarBooks: ").Append(SimilarBooks).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
