/**
 * API League
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: mail@apileague.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIRandomTriviaAPI_200_response.h
 *
 * 
 */

#ifndef OAIRandomTriviaAPI_200_response_H
#define OAIRandomTriviaAPI_200_response_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIRandomTriviaAPI_200_response : public OAIObject {
public:
    OAIRandomTriviaAPI_200_response();
    OAIRandomTriviaAPI_200_response(QString json);
    ~OAIRandomTriviaAPI_200_response() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getTrivia() const;
    void setTrivia(const QString &trivia);
    bool is_trivia_Set() const;
    bool is_trivia_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_trivia;
    bool m_trivia_isSet;
    bool m_trivia_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIRandomTriviaAPI_200_response)

#endif // OAIRandomTriviaAPI_200_response_H
