/**
 * API League
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.6.4
 * Contact: mail@apileague.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIRetrieveRecipeInformationAPI_200_response_nutrition.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIRetrieveRecipeInformationAPI_200_response_nutrition::OAIRetrieveRecipeInformationAPI_200_response_nutrition(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIRetrieveRecipeInformationAPI_200_response_nutrition::OAIRetrieveRecipeInformationAPI_200_response_nutrition() {
    this->initializeModel();
}

OAIRetrieveRecipeInformationAPI_200_response_nutrition::~OAIRetrieveRecipeInformationAPI_200_response_nutrition() {}

void OAIRetrieveRecipeInformationAPI_200_response_nutrition::initializeModel() {

    m_weight_per_serving_isSet = false;
    m_weight_per_serving_isValid = false;

    m_caloric_breakdown_isSet = false;
    m_caloric_breakdown_isValid = false;

    m_flavonoids_isSet = false;
    m_flavonoids_isValid = false;

    m_ingredient_breakdown_isSet = false;
    m_ingredient_breakdown_isValid = false;

    m_properties_isSet = false;
    m_properties_isValid = false;

    m_nutrients_isSet = false;
    m_nutrients_isValid = false;
}

void OAIRetrieveRecipeInformationAPI_200_response_nutrition::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIRetrieveRecipeInformationAPI_200_response_nutrition::fromJsonObject(QJsonObject json) {

    m_weight_per_serving_isValid = ::OpenAPI::fromJsonValue(m_weight_per_serving, json[QString("weight_per_serving")]);
    m_weight_per_serving_isSet = !json[QString("weight_per_serving")].isNull() && m_weight_per_serving_isValid;

    m_caloric_breakdown_isValid = ::OpenAPI::fromJsonValue(m_caloric_breakdown, json[QString("caloric_breakdown")]);
    m_caloric_breakdown_isSet = !json[QString("caloric_breakdown")].isNull() && m_caloric_breakdown_isValid;

    m_flavonoids_isValid = ::OpenAPI::fromJsonValue(m_flavonoids, json[QString("flavonoids")]);
    m_flavonoids_isSet = !json[QString("flavonoids")].isNull() && m_flavonoids_isValid;

    m_ingredient_breakdown_isValid = ::OpenAPI::fromJsonValue(m_ingredient_breakdown, json[QString("ingredient_breakdown")]);
    m_ingredient_breakdown_isSet = !json[QString("ingredient_breakdown")].isNull() && m_ingredient_breakdown_isValid;

    m_properties_isValid = ::OpenAPI::fromJsonValue(m_properties, json[QString("properties")]);
    m_properties_isSet = !json[QString("properties")].isNull() && m_properties_isValid;

    m_nutrients_isValid = ::OpenAPI::fromJsonValue(m_nutrients, json[QString("nutrients")]);
    m_nutrients_isSet = !json[QString("nutrients")].isNull() && m_nutrients_isValid;
}

QString OAIRetrieveRecipeInformationAPI_200_response_nutrition::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIRetrieveRecipeInformationAPI_200_response_nutrition::asJsonObject() const {
    QJsonObject obj;
    if (m_weight_per_serving.isSet()) {
        obj.insert(QString("weight_per_serving"), ::OpenAPI::toJsonValue(m_weight_per_serving));
    }
    if (m_caloric_breakdown.isSet()) {
        obj.insert(QString("caloric_breakdown"), ::OpenAPI::toJsonValue(m_caloric_breakdown));
    }
    if (m_flavonoids.size() > 0) {
        obj.insert(QString("flavonoids"), ::OpenAPI::toJsonValue(m_flavonoids));
    }
    if (m_ingredient_breakdown.size() > 0) {
        obj.insert(QString("ingredient_breakdown"), ::OpenAPI::toJsonValue(m_ingredient_breakdown));
    }
    if (m_properties.size() > 0) {
        obj.insert(QString("properties"), ::OpenAPI::toJsonValue(m_properties));
    }
    if (m_nutrients.size() > 0) {
        obj.insert(QString("nutrients"), ::OpenAPI::toJsonValue(m_nutrients));
    }
    return obj;
}

OAISearchDrinksAPI_200_response_drinks_inner_nutrition_weight_per_serving OAIRetrieveRecipeInformationAPI_200_response_nutrition::getWeightPerServing() const {
    return m_weight_per_serving;
}
void OAIRetrieveRecipeInformationAPI_200_response_nutrition::setWeightPerServing(const OAISearchDrinksAPI_200_response_drinks_inner_nutrition_weight_per_serving &weight_per_serving) {
    m_weight_per_serving = weight_per_serving;
    m_weight_per_serving_isSet = true;
}

bool OAIRetrieveRecipeInformationAPI_200_response_nutrition::is_weight_per_serving_Set() const{
    return m_weight_per_serving_isSet;
}

bool OAIRetrieveRecipeInformationAPI_200_response_nutrition::is_weight_per_serving_Valid() const{
    return m_weight_per_serving_isValid;
}

OAISearchDrinksAPI_200_response_drinks_inner_nutrition_caloric_breakdown OAIRetrieveRecipeInformationAPI_200_response_nutrition::getCaloricBreakdown() const {
    return m_caloric_breakdown;
}
void OAIRetrieveRecipeInformationAPI_200_response_nutrition::setCaloricBreakdown(const OAISearchDrinksAPI_200_response_drinks_inner_nutrition_caloric_breakdown &caloric_breakdown) {
    m_caloric_breakdown = caloric_breakdown;
    m_caloric_breakdown_isSet = true;
}

bool OAIRetrieveRecipeInformationAPI_200_response_nutrition::is_caloric_breakdown_Set() const{
    return m_caloric_breakdown_isSet;
}

bool OAIRetrieveRecipeInformationAPI_200_response_nutrition::is_caloric_breakdown_Valid() const{
    return m_caloric_breakdown_isValid;
}

QList<OAISearchDrinksAPI_200_response_drinks_inner_nutrition_flavonoids_inner> OAIRetrieveRecipeInformationAPI_200_response_nutrition::getFlavonoids() const {
    return m_flavonoids;
}
void OAIRetrieveRecipeInformationAPI_200_response_nutrition::setFlavonoids(const QList<OAISearchDrinksAPI_200_response_drinks_inner_nutrition_flavonoids_inner> &flavonoids) {
    m_flavonoids = flavonoids;
    m_flavonoids_isSet = true;
}

bool OAIRetrieveRecipeInformationAPI_200_response_nutrition::is_flavonoids_Set() const{
    return m_flavonoids_isSet;
}

bool OAIRetrieveRecipeInformationAPI_200_response_nutrition::is_flavonoids_Valid() const{
    return m_flavonoids_isValid;
}

QList<OAIRetrieveRecipeInformationAPI_200_response_nutrition_ingredient_breakdown_inner> OAIRetrieveRecipeInformationAPI_200_response_nutrition::getIngredientBreakdown() const {
    return m_ingredient_breakdown;
}
void OAIRetrieveRecipeInformationAPI_200_response_nutrition::setIngredientBreakdown(const QList<OAIRetrieveRecipeInformationAPI_200_response_nutrition_ingredient_breakdown_inner> &ingredient_breakdown) {
    m_ingredient_breakdown = ingredient_breakdown;
    m_ingredient_breakdown_isSet = true;
}

bool OAIRetrieveRecipeInformationAPI_200_response_nutrition::is_ingredient_breakdown_Set() const{
    return m_ingredient_breakdown_isSet;
}

bool OAIRetrieveRecipeInformationAPI_200_response_nutrition::is_ingredient_breakdown_Valid() const{
    return m_ingredient_breakdown_isValid;
}

QList<OAISearchRecipesAPI_200_response_recipes_inner_nutrition_nutrients_inner> OAIRetrieveRecipeInformationAPI_200_response_nutrition::getProperties() const {
    return m_properties;
}
void OAIRetrieveRecipeInformationAPI_200_response_nutrition::setProperties(const QList<OAISearchRecipesAPI_200_response_recipes_inner_nutrition_nutrients_inner> &properties) {
    m_properties = properties;
    m_properties_isSet = true;
}

bool OAIRetrieveRecipeInformationAPI_200_response_nutrition::is_properties_Set() const{
    return m_properties_isSet;
}

bool OAIRetrieveRecipeInformationAPI_200_response_nutrition::is_properties_Valid() const{
    return m_properties_isValid;
}

QList<OAISearchDrinksAPI_200_response_drinks_inner_nutrition_nutrients_inner> OAIRetrieveRecipeInformationAPI_200_response_nutrition::getNutrients() const {
    return m_nutrients;
}
void OAIRetrieveRecipeInformationAPI_200_response_nutrition::setNutrients(const QList<OAISearchDrinksAPI_200_response_drinks_inner_nutrition_nutrients_inner> &nutrients) {
    m_nutrients = nutrients;
    m_nutrients_isSet = true;
}

bool OAIRetrieveRecipeInformationAPI_200_response_nutrition::is_nutrients_Set() const{
    return m_nutrients_isSet;
}

bool OAIRetrieveRecipeInformationAPI_200_response_nutrition::is_nutrients_Valid() const{
    return m_nutrients_isValid;
}

bool OAIRetrieveRecipeInformationAPI_200_response_nutrition::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_weight_per_serving.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_caloric_breakdown.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_flavonoids.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_ingredient_breakdown.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_properties.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_nutrients.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIRetrieveRecipeInformationAPI_200_response_nutrition::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
