/**
 * API League
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: mail@apileague.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISearchDrinks_200_response_drinks_inner_nutrition.h
 *
 * 
 */

#ifndef OAISearchDrinks_200_response_drinks_inner_nutrition_H
#define OAISearchDrinks_200_response_drinks_inner_nutrition_H

#include <QJsonObject>

#include "OAISearchDrinks_200_response_drinks_inner_nutrition_caloric_breakdown.h"
#include "OAISearchDrinks_200_response_drinks_inner_nutrition_flavonoids_inner.h"
#include "OAISearchDrinks_200_response_drinks_inner_nutrition_ingredient_breakdown_inner.h"
#include "OAISearchDrinks_200_response_drinks_inner_nutrition_nutrients_inner.h"
#include "OAISearchDrinks_200_response_drinks_inner_nutrition_weight_per_serving.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAISearchDrinks_200_response_drinks_inner_nutrition_weight_per_serving;
class OAISearchDrinks_200_response_drinks_inner_nutrition_caloric_breakdown;
class OAISearchDrinks_200_response_drinks_inner_nutrition_flavonoids_inner;
class OAISearchDrinks_200_response_drinks_inner_nutrition_ingredient_breakdown_inner;
class OAISearchDrinks_200_response_drinks_inner_nutrition_nutrients_inner;

class OAISearchDrinks_200_response_drinks_inner_nutrition : public OAIObject {
public:
    OAISearchDrinks_200_response_drinks_inner_nutrition();
    OAISearchDrinks_200_response_drinks_inner_nutrition(QString json);
    ~OAISearchDrinks_200_response_drinks_inner_nutrition() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAISearchDrinks_200_response_drinks_inner_nutrition_weight_per_serving getWeightPerServing() const;
    void setWeightPerServing(const OAISearchDrinks_200_response_drinks_inner_nutrition_weight_per_serving &weight_per_serving);
    bool is_weight_per_serving_Set() const;
    bool is_weight_per_serving_Valid() const;

    OAISearchDrinks_200_response_drinks_inner_nutrition_caloric_breakdown getCaloricBreakdown() const;
    void setCaloricBreakdown(const OAISearchDrinks_200_response_drinks_inner_nutrition_caloric_breakdown &caloric_breakdown);
    bool is_caloric_breakdown_Set() const;
    bool is_caloric_breakdown_Valid() const;

    QList<OAISearchDrinks_200_response_drinks_inner_nutrition_flavonoids_inner> getFlavonoids() const;
    void setFlavonoids(const QList<OAISearchDrinks_200_response_drinks_inner_nutrition_flavonoids_inner> &flavonoids);
    bool is_flavonoids_Set() const;
    bool is_flavonoids_Valid() const;

    QList<OAISearchDrinks_200_response_drinks_inner_nutrition_ingredient_breakdown_inner> getIngredientBreakdown() const;
    void setIngredientBreakdown(const QList<OAISearchDrinks_200_response_drinks_inner_nutrition_ingredient_breakdown_inner> &ingredient_breakdown);
    bool is_ingredient_breakdown_Set() const;
    bool is_ingredient_breakdown_Valid() const;

    QList<OAISearchDrinks_200_response_drinks_inner_nutrition_flavonoids_inner> getProperties() const;
    void setProperties(const QList<OAISearchDrinks_200_response_drinks_inner_nutrition_flavonoids_inner> &properties);
    bool is_properties_Set() const;
    bool is_properties_Valid() const;

    QList<OAISearchDrinks_200_response_drinks_inner_nutrition_nutrients_inner> getNutrients() const;
    void setNutrients(const QList<OAISearchDrinks_200_response_drinks_inner_nutrition_nutrients_inner> &nutrients);
    bool is_nutrients_Set() const;
    bool is_nutrients_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAISearchDrinks_200_response_drinks_inner_nutrition_weight_per_serving m_weight_per_serving;
    bool m_weight_per_serving_isSet;
    bool m_weight_per_serving_isValid;

    OAISearchDrinks_200_response_drinks_inner_nutrition_caloric_breakdown m_caloric_breakdown;
    bool m_caloric_breakdown_isSet;
    bool m_caloric_breakdown_isValid;

    QList<OAISearchDrinks_200_response_drinks_inner_nutrition_flavonoids_inner> m_flavonoids;
    bool m_flavonoids_isSet;
    bool m_flavonoids_isValid;

    QList<OAISearchDrinks_200_response_drinks_inner_nutrition_ingredient_breakdown_inner> m_ingredient_breakdown;
    bool m_ingredient_breakdown_isSet;
    bool m_ingredient_breakdown_isValid;

    QList<OAISearchDrinks_200_response_drinks_inner_nutrition_flavonoids_inner> m_properties;
    bool m_properties_isSet;
    bool m_properties_isValid;

    QList<OAISearchDrinks_200_response_drinks_inner_nutrition_nutrients_inner> m_nutrients;
    bool m_nutrients_isSet;
    bool m_nutrients_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISearchDrinks_200_response_drinks_inner_nutrition)

#endif // OAISearchDrinks_200_response_drinks_inner_nutrition_H
