/**
 * API League
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.7.0
 * Contact: mail@apileague.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAITopNewsAPI_200_response_top_news_inner.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAITopNewsAPI_200_response_top_news_inner::OAITopNewsAPI_200_response_top_news_inner(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAITopNewsAPI_200_response_top_news_inner::OAITopNewsAPI_200_response_top_news_inner() {
    this->initializeModel();
}

OAITopNewsAPI_200_response_top_news_inner::~OAITopNewsAPI_200_response_top_news_inner() {}

void OAITopNewsAPI_200_response_top_news_inner::initializeModel() {

    m_news_isSet = false;
    m_news_isValid = false;
}

void OAITopNewsAPI_200_response_top_news_inner::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAITopNewsAPI_200_response_top_news_inner::fromJsonObject(QJsonObject json) {

    m_news_isValid = ::OpenAPI::fromJsonValue(m_news, json[QString("news")]);
    m_news_isSet = !json[QString("news")].isNull() && m_news_isValid;
}

QString OAITopNewsAPI_200_response_top_news_inner::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAITopNewsAPI_200_response_top_news_inner::asJsonObject() const {
    QJsonObject obj;
    if (m_news.size() > 0) {
        obj.insert(QString("news"), ::OpenAPI::toJsonValue(m_news));
    }
    return obj;
}

QList<OAITopNewsAPI_200_response_top_news_inner_news_inner> OAITopNewsAPI_200_response_top_news_inner::getNews() const {
    return m_news;
}
void OAITopNewsAPI_200_response_top_news_inner::setNews(const QList<OAITopNewsAPI_200_response_top_news_inner_news_inner> &news) {
    m_news = news;
    m_news_isSet = true;
}

bool OAITopNewsAPI_200_response_top_news_inner::is_news_Set() const{
    return m_news_isSet;
}

bool OAITopNewsAPI_200_response_top_news_inner::is_news_Valid() const{
    return m_news_isValid;
}

bool OAITopNewsAPI_200_response_top_news_inner::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_news.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAITopNewsAPI_200_response_top_news_inner::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
