/*
 * API League
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@apileague.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.apileague.client.model;

import com.apileague.client.model.InlineResponse20018SkimmabilityMainscores;
import com.apileague.client.model.InlineResponse20018SkimmabilitySubscores;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse20018Skimmability
 */
public class InlineResponse20018SkimmabilityTest {
    private final InlineResponse20018Skimmability model = new InlineResponse20018Skimmability();

    /**
     * Model tests for InlineResponse20018Skimmability
     */
    @Test
    public void testInlineResponse20018Skimmability() {
        // TODO: test InlineResponse20018Skimmability
    }

    /**
     * Test the property 'mainscores'
     */
    @Test
    public void mainscoresTest() {
        // TODO: test mainscores
    }

    /**
     * Test the property 'subscores'
     */
    @Test
    public void subscoresTest() {
        // TODO: test subscores
    }

}
