/*
 * API League
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: mail@apileague.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.apileague.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RetrieveGameById200ResponsePlaytime
 */
public class RetrieveGameById200ResponsePlaytimeTest {
    private final RetrieveGameById200ResponsePlaytime model = new RetrieveGameById200ResponsePlaytime();

    /**
     * Model tests for RetrieveGameById200ResponsePlaytime
     */
    @Test
    public void testRetrieveGameById200ResponsePlaytime() {
        // TODO: test RetrieveGameById200ResponsePlaytime
    }

    /**
     * Test the property 'percentiles'
     */
    @Test
    public void percentilesTest() {
        // TODO: test percentiles
    }

    /**
     * Test the property 'min'
     */
    @Test
    public void minTest() {
        // TODO: test min
    }

    /**
     * Test the property 'median'
     */
    @Test
    public void medianTest() {
        // TODO: test median
    }

    /**
     * Test the property 'max'
     */
    @Test
    public void maxTest() {
        // TODO: test max
    }

    /**
     * Test the property 'mean'
     */
    @Test
    public void meanTest() {
        // TODO: test mean
    }

    /**
     * Test the property 'mentions'
     */
    @Test
    public void mentionsTest() {
        // TODO: test mentions
    }

}
