/*
 * API League
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: mail@apileague.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.apileague.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RetrievePageRankAPI200Response
 */
public class RetrievePageRankAPI200ResponseTest {
    private final RetrievePageRankAPI200Response model = new RetrievePageRankAPI200Response();

    /**
     * Model tests for RetrievePageRankAPI200Response
     */
    @Test
    public void testRetrievePageRankAPI200Response() {
        // TODO: test RetrievePageRankAPI200Response
    }

    /**
     * Test the property 'pageRank'
     */
    @Test
    public void pageRankTest() {
        // TODO: test pageRank
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'percentile'
     */
    @Test
    public void percentileTest() {
        // TODO: test percentile
    }

}
