/*
 * API League
 *
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.7.0
 * Contact: mail@apileague.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopNewsApi200ResponseTopNewsInner {
    #[serde(rename = "news", skip_serializing_if = "Option::is_none")]
    pub news: Option<Vec<models::TopNewsApi200ResponseTopNewsInnerNewsInner>>,
}

impl TopNewsApi200ResponseTopNewsInner {
    pub fn new() -> TopNewsApi200ResponseTopNewsInner {
        TopNewsApi200ResponseTopNewsInner {
            news: None,
        }
    }
}

