/**
 * API League
 * API League is a Hub for World Class APIs.
 *
 * OpenAPI spec version: 1.7.0
 * Contact: mail@apileague.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SearchDrinksAPI200ResponseDrinksInnerNutritionNutrientsInner } from '../models/SearchDrinksAPI200ResponseDrinksInnerNutritionNutrientsInner';
import { HttpFile } from '../http/http';

export class RetrieveRecipeInformationAPI200ResponseNutritionIngredientBreakdownInner {
    'name'?: string | null;
    'amount'?: number;
    'unit'?: string | null;
    'id'?: number;
    'nutrients'?: Array<SearchDrinksAPI200ResponseDrinksInnerNutritionNutrientsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "nutrients",
            "baseName": "nutrients",
            "type": "Array<SearchDrinksAPI200ResponseDrinksInnerNutritionNutrientsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RetrieveRecipeInformationAPI200ResponseNutritionIngredientBreakdownInner.attributeTypeMap;
    }

    public constructor() {
    }
}

