/**
 * API League
 * API League is a Hub for World Class APIs.
 *
 * OpenAPI spec version: 1.0
 * Contact: mail@apileague.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SearchRecipes200ResponseRecipesInner } from '../models/SearchRecipes200ResponseRecipesInner';
import { HttpFile } from '../http/http';

export class SearchRecipes200Response {
    'offset'?: number;
    'number'?: number;
    'recipes'?: Array<SearchRecipes200ResponseRecipesInner>;
    'totalResults'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "offset",
            "baseName": "offset",
            "type": "number",
            "format": ""
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "number",
            "format": ""
        },
        {
            "name": "recipes",
            "baseName": "recipes",
            "type": "Array<SearchRecipes200ResponseRecipesInner>",
            "format": ""
        },
        {
            "name": "totalResults",
            "baseName": "total_results",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchRecipes200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

