/**
 * API League
 * API League is a Hub for World Class APIs.
 *
 * OpenAPI spec version: 1.8.1
 * Contact: mail@apileague.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SearchGamesAPI200ResponseActiveFilterOptionsInnerValuesInner } from '../models/SearchGamesAPI200ResponseActiveFilterOptionsInnerValuesInner';
import { HttpFile } from '../http/http';

export class SearchGamesAPI200ResponseActiveFilterOptionsInner {
    'key'?: string | null;
    'connection'?: string | null;
    'values'?: Array<SearchGamesAPI200ResponseActiveFilterOptionsInnerValuesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        },
        {
            "name": "connection",
            "baseName": "connection",
            "type": "string",
            "format": ""
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<SearchGamesAPI200ResponseActiveFilterOptionsInnerValuesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchGamesAPI200ResponseActiveFilterOptionsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

