/**
 * API League
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@apileague.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.apileague.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse20018StyleSubscores {
  
  @SerializedName("abbreviation_score")
  private List<Integer> abbreviationScore = null;
  @SerializedName("style_score")
  private List<Integer> styleScore = null;
  @SerializedName("spelling_score")
  private List<Integer> spellingScore = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Integer> getAbbreviationScore() {
    return abbreviationScore;
  }
  public void setAbbreviationScore(List<Integer> abbreviationScore) {
    this.abbreviationScore = abbreviationScore;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Integer> getStyleScore() {
    return styleScore;
  }
  public void setStyleScore(List<Integer> styleScore) {
    this.styleScore = styleScore;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Integer> getSpellingScore() {
    return spellingScore;
  }
  public void setSpellingScore(List<Integer> spellingScore) {
    this.spellingScore = spellingScore;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20018StyleSubscores inlineResponse20018StyleSubscores = (InlineResponse20018StyleSubscores) o;
    return (this.abbreviationScore == null ? inlineResponse20018StyleSubscores.abbreviationScore == null : this.abbreviationScore.equals(inlineResponse20018StyleSubscores.abbreviationScore)) &&
        (this.styleScore == null ? inlineResponse20018StyleSubscores.styleScore == null : this.styleScore.equals(inlineResponse20018StyleSubscores.styleScore)) &&
        (this.spellingScore == null ? inlineResponse20018StyleSubscores.spellingScore == null : this.spellingScore.equals(inlineResponse20018StyleSubscores.spellingScore));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.abbreviationScore == null ? 0: this.abbreviationScore.hashCode());
    result = 31 * result + (this.styleScore == null ? 0: this.styleScore.hashCode());
    result = 31 * result + (this.spellingScore == null ? 0: this.spellingScore.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20018StyleSubscores {\n");
    
    sb.append("  abbreviationScore: ").append(abbreviationScore).append("\n");
    sb.append("  styleScore: ").append(styleScore).append("\n");
    sb.append("  spellingScore: ").append(spellingScore).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
