/**
 * API League
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: mail@apileague.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.apileague.client.model;

import com.apileague.client.model.SearchDrinksAPI200ResponseDrinksInnerInstructionsInnerStepsInner;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SearchDrinksAPI200ResponseDrinksInnerInstructionsInner {
  
  @SerializedName("name")
  private String name = null;
  @SerializedName("steps")
  private List<SearchDrinksAPI200ResponseDrinksInnerInstructionsInnerStepsInner> steps = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<SearchDrinksAPI200ResponseDrinksInnerInstructionsInnerStepsInner> getSteps() {
    return steps;
  }
  public void setSteps(List<SearchDrinksAPI200ResponseDrinksInnerInstructionsInnerStepsInner> steps) {
    this.steps = steps;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchDrinksAPI200ResponseDrinksInnerInstructionsInner searchDrinksAPI200ResponseDrinksInnerInstructionsInner = (SearchDrinksAPI200ResponseDrinksInnerInstructionsInner) o;
    return (this.name == null ? searchDrinksAPI200ResponseDrinksInnerInstructionsInner.name == null : this.name.equals(searchDrinksAPI200ResponseDrinksInnerInstructionsInner.name)) &&
        (this.steps == null ? searchDrinksAPI200ResponseDrinksInnerInstructionsInner.steps == null : this.steps.equals(searchDrinksAPI200ResponseDrinksInnerInstructionsInner.steps));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.steps == null ? 0: this.steps.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchDrinksAPI200ResponseDrinksInnerInstructionsInner {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("  steps: ").append(steps).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
