/**
 * API League
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@apileague.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInline_response_200_23.h
 *
 * 
 */

#ifndef OAIInline_response_200_23_H
#define OAIInline_response_200_23_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIInline_response_200_23 : public OAIObject {
public:
    OAIInline_response_200_23();
    OAIInline_response_200_23(QString json);
    ~OAIInline_response_200_23() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getTaggedText() const;
    void setTaggedText(const QString &tagged_text);
    bool is_tagged_text_Set() const;
    bool is_tagged_text_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString tagged_text;
    bool m_tagged_text_isSet;
    bool m_tagged_text_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIInline_response_200_23)

#endif // OAIInline_response_200_23_H
