--[[
  API League

  API League is a Hub for World Class APIs.

  The version of the OpenAPI document: 1.7.0
  Contact: mail@apileague.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for apileague.api.books_api
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("books_api", function()
  local apileague_books_api = require "apileague.api.books_api"
  -- unit tests for find_similar_books_api
  describe("find_similar_books_api test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for search_books_api
  describe("search_books_api test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
