/*
API League

API League is a Hub for World Class APIs.

API version: 1.8.1
Contact: mail@apileague.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apileague

import (
	"encoding/json"
)

// checks if the RandomQuoteAPI200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RandomQuoteAPI200Response{}

// RandomQuoteAPI200Response struct for RandomQuoteAPI200Response
type RandomQuoteAPI200Response struct {
	Author NullableString `json:"author,omitempty"`
	Quote NullableString `json:"quote,omitempty"`
}

// NewRandomQuoteAPI200Response instantiates a new RandomQuoteAPI200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRandomQuoteAPI200Response() *RandomQuoteAPI200Response {
	this := RandomQuoteAPI200Response{}
	return &this
}

// NewRandomQuoteAPI200ResponseWithDefaults instantiates a new RandomQuoteAPI200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRandomQuoteAPI200ResponseWithDefaults() *RandomQuoteAPI200Response {
	this := RandomQuoteAPI200Response{}
	return &this
}

// GetAuthor returns the Author field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RandomQuoteAPI200Response) GetAuthor() string {
	if o == nil || IsNil(o.Author.Get()) {
		var ret string
		return ret
	}
	return *o.Author.Get()
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RandomQuoteAPI200Response) GetAuthorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Author.Get(), o.Author.IsSet()
}

// HasAuthor returns a boolean if a field has been set.
func (o *RandomQuoteAPI200Response) HasAuthor() bool {
	if o != nil && o.Author.IsSet() {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given NullableString and assigns it to the Author field.
func (o *RandomQuoteAPI200Response) SetAuthor(v string) {
	o.Author.Set(&v)
}
// SetAuthorNil sets the value for Author to be an explicit nil
func (o *RandomQuoteAPI200Response) SetAuthorNil() {
	o.Author.Set(nil)
}

// UnsetAuthor ensures that no value is present for Author, not even an explicit nil
func (o *RandomQuoteAPI200Response) UnsetAuthor() {
	o.Author.Unset()
}

// GetQuote returns the Quote field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RandomQuoteAPI200Response) GetQuote() string {
	if o == nil || IsNil(o.Quote.Get()) {
		var ret string
		return ret
	}
	return *o.Quote.Get()
}

// GetQuoteOk returns a tuple with the Quote field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RandomQuoteAPI200Response) GetQuoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Quote.Get(), o.Quote.IsSet()
}

// HasQuote returns a boolean if a field has been set.
func (o *RandomQuoteAPI200Response) HasQuote() bool {
	if o != nil && o.Quote.IsSet() {
		return true
	}

	return false
}

// SetQuote gets a reference to the given NullableString and assigns it to the Quote field.
func (o *RandomQuoteAPI200Response) SetQuote(v string) {
	o.Quote.Set(&v)
}
// SetQuoteNil sets the value for Quote to be an explicit nil
func (o *RandomQuoteAPI200Response) SetQuoteNil() {
	o.Quote.Set(nil)
}

// UnsetQuote ensures that no value is present for Quote, not even an explicit nil
func (o *RandomQuoteAPI200Response) UnsetQuote() {
	o.Quote.Unset()
}

func (o RandomQuoteAPI200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RandomQuoteAPI200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Author.IsSet() {
		toSerialize["author"] = o.Author.Get()
	}
	if o.Quote.IsSet() {
		toSerialize["quote"] = o.Quote.Get()
	}
	return toSerialize, nil
}

type NullableRandomQuoteAPI200Response struct {
	value *RandomQuoteAPI200Response
	isSet bool
}

func (v NullableRandomQuoteAPI200Response) Get() *RandomQuoteAPI200Response {
	return v.value
}

func (v *NullableRandomQuoteAPI200Response) Set(val *RandomQuoteAPI200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRandomQuoteAPI200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRandomQuoteAPI200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRandomQuoteAPI200Response(val *RandomQuoteAPI200Response) *NullableRandomQuoteAPI200Response {
	return &NullableRandomQuoteAPI200Response{value: val, isSet: true}
}

func (v NullableRandomQuoteAPI200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRandomQuoteAPI200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


