/*
API League

API League is a Hub for World Class APIs.

API version: 1.7.0
Contact: mail@apileague.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apileague

import (
	"encoding/json"
)

// checks if the RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures{}

// RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures struct for RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures
type RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures struct {
	Metric *SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric `json:"metric,omitempty"`
	Us *SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric `json:"us,omitempty"`
}

// NewRetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures instantiates a new RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures() *RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures {
	this := RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures{}
	return &this
}

// NewRetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasuresWithDefaults instantiates a new RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasuresWithDefaults() *RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures {
	this := RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures{}
	return &this
}

// GetMetric returns the Metric field value if set, zero value otherwise.
func (o *RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures) GetMetric() SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric {
	if o == nil || IsNil(o.Metric) {
		var ret SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric
		return ret
	}
	return *o.Metric
}

// GetMetricOk returns a tuple with the Metric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures) GetMetricOk() (*SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric, bool) {
	if o == nil || IsNil(o.Metric) {
		return nil, false
	}
	return o.Metric, true
}

// HasMetric returns a boolean if a field has been set.
func (o *RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures) HasMetric() bool {
	if o != nil && !IsNil(o.Metric) {
		return true
	}

	return false
}

// SetMetric gets a reference to the given SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric and assigns it to the Metric field.
func (o *RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures) SetMetric(v SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric) {
	o.Metric = &v
}

// GetUs returns the Us field value if set, zero value otherwise.
func (o *RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures) GetUs() SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric {
	if o == nil || IsNil(o.Us) {
		var ret SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric
		return ret
	}
	return *o.Us
}

// GetUsOk returns a tuple with the Us field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures) GetUsOk() (*SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric, bool) {
	if o == nil || IsNil(o.Us) {
		return nil, false
	}
	return o.Us, true
}

// HasUs returns a boolean if a field has been set.
func (o *RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures) HasUs() bool {
	if o != nil && !IsNil(o.Us) {
		return true
	}

	return false
}

// SetUs gets a reference to the given SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric and assigns it to the Us field.
func (o *RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures) SetUs(v SearchDrinksAPI200ResponseDrinksInnerIngredientsInnerMeasuresMetric) {
	o.Us = &v
}

func (o RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metric) {
		toSerialize["metric"] = o.Metric
	}
	if !IsNil(o.Us) {
		toSerialize["us"] = o.Us
	}
	return toSerialize, nil
}

type NullableRetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures struct {
	value *RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures
	isSet bool
}

func (v NullableRetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures) Get() *RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures {
	return v.value
}

func (v *NullableRetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures) Set(val *RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures) {
	v.value = val
	v.isSet = true
}

func (v NullableRetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures) IsSet() bool {
	return v.isSet
}

func (v *NullableRetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures(val *RetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures) *NullableRetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures {
	return &NullableRetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures{value: val, isSet: true}
}

func (v NullableRetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetrieveRecipeInformationAPI200ResponseIngredientsInnerMeasures) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


