#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* API League
* API League is a Hub for World Class APIs.
*
* The version of the OpenAPI document: 1.0
* Contact: mail@apileague.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIInlineResponse20018ReadabilityMainscores.h"
#import "OAIInlineResponse20018StyleSubscores.h"
@protocol OAIInlineResponse20018ReadabilityMainscores;
@class OAIInlineResponse20018ReadabilityMainscores;
@protocol OAIInlineResponse20018StyleSubscores;
@class OAIInlineResponse20018StyleSubscores;



@protocol OAIInlineResponse20018Style
@end

@interface OAIInlineResponse20018Style : OAIObject


@property(nonatomic) OAIInlineResponse20018ReadabilityMainscores* mainscores;

@property(nonatomic) OAIInlineResponse20018StyleSubscores* subscores;

@end
