/**
 * API League
 *
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@apileague.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.apileague.client.model

import com.apileague.client.model.InlineResponse20019Interestingness
import com.apileague.client.model.InlineResponse20019Readability
import com.apileague.client.model.InlineResponse20019Skimmability
import com.apileague.client.model.InlineResponse20019Style

import com.squareup.moshi.Json

/**
 * 
 *
 * @param numberOfWords 
 * @param numberOfSentences 
 * @param readability 
 * @param skimmability 
 * @param interestingness 
 * @param style 
 * @param totalScore 
 */

data class InlineResponse20019 (

    @Json(name = "number_of_words")
    val numberOfWords: kotlin.Int? = null,

    @Json(name = "number_of_sentences")
    val numberOfSentences: kotlin.Int? = null,

    @Json(name = "readability")
    val readability: InlineResponse20019Readability? = null,

    @Json(name = "skimmability")
    val skimmability: InlineResponse20019Skimmability? = null,

    @Json(name = "interestingness")
    val interestingness: InlineResponse20019Interestingness? = null,

    @Json(name = "style")
    val style: InlineResponse20019Style? = null,

    @Json(name = "total_score")
    val totalScore: java.math.BigDecimal? = null

)

