/**
 * API League
 *
 * API League is a Hub for World Class APIs.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@apileague.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.apileague.client.model

import com.apileague.client.model.InlineResponse2002News

import com.squareup.moshi.Json

/**
 * 
 *
 * @param offset 
 * @param number 
 * @param available 
 * @param news 
 */

data class InlineResponse2002 (

    @Json(name = "offset")
    val offset: kotlin.Int? = null,

    @Json(name = "number")
    val number: kotlin.Int? = null,

    @Json(name = "available")
    val available: kotlin.Int? = null,

    @Json(name = "news")
    val news: kotlin.collections.List<InlineResponse2002News>? = null

)

