/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.apileague.client.model

import com.apileague.client.model.ScoreTextAPI200ResponseReadabilityMainscores
import com.apileague.client.model.ScoreTextAPI200ResponseStyleSubscores

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param mainscores 
 * @param subscores 
 */


data class ScoreTextAPI200ResponseStyle (

    @Json(name = "mainscores")
    val mainscores: ScoreTextAPI200ResponseReadabilityMainscores? = null,

    @Json(name = "subscores")
    val subscores: ScoreTextAPI200ResponseStyleSubscores? = null

) {


}

