/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.apileague.client.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param link 
 */


data class SearchRoyaltyFreeImages200ResponseImagesInnerLicense (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "link")
    val link: kotlin.String? = null

)

