/**
 * API League
 * API League is a Hub for World Class APIs.
 *
 * OpenAPI spec version: 1.0
 * Contact: mail@apileague.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse20018SkimmabilityMainscores } from './InlineResponse20018SkimmabilityMainscores';
import { InlineResponse20018SkimmabilitySubscores } from './InlineResponse20018SkimmabilitySubscores';
import { HttpFile } from '../http/http';

export class InlineResponse20018Skimmability {
    'mainscores'?: InlineResponse20018SkimmabilityMainscores;
    'subscores'?: InlineResponse20018SkimmabilitySubscores;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mainscores",
            "baseName": "mainscores",
            "type": "InlineResponse20018SkimmabilityMainscores",
            "format": ""
        },
        {
            "name": "subscores",
            "baseName": "subscores",
            "type": "InlineResponse20018SkimmabilitySubscores",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20018Skimmability.attributeTypeMap;
    }

    public constructor() {
    }
}

