# NOTE: This file is auto generated by OpenAPI Generator 7.8.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APILeague.Model.RetrieveRecipeInformationApi200ResponseIngredientsInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :image,
    :name_clean,
    :amount,
    :unit,
    :measures,
    :original,
    :meta,
    :original_name,
    :name,
    :id,
    :aisle,
    :consistency
  ]

  @type t :: %__MODULE__{
    :image => String.t | nil,
    :name_clean => String.t | nil,
    :amount => float() | nil,
    :unit => String.t | nil,
    :measures => APILeague.Model.RetrieveRecipeInformationApi200ResponseIngredientsInnerMeasures.t | nil,
    :original => String.t | nil,
    :meta => [String.t] | nil,
    :original_name => String.t | nil,
    :name => String.t | nil,
    :id => integer() | nil,
    :aisle => String.t | nil,
    :consistency => String.t | nil
  }

  alias APILeague.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:measures, :struct, APILeague.Model.RetrieveRecipeInformationApi200ResponseIngredientsInnerMeasures)
  end
end

